In [2]:
import os

In [3]:
os.chdir('C:/Users/User/Desktop/datasets')

In [21]:
import numpy as np
import pandas as pd
d=pd.read_csv("DelayedFlights.csv")
d

Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
0                 0  2008      1           3          4     2003        1955   
1                 1  2008      1           3          4      754         735   
2                 2  2008      1           3          4      628         620   
3                 4  2008      1           3          4     1829        1755   
4                 5  2008      1           3          4     1940        1915   
5                 6  2008      1           3          4     1937        1830   
6                10  2008      1           3          4      706         700   
7                11  2008      1           3          4     1644        1510   
8                15  2008      1           3          4     1029        1020   
9                16  2008      1           3          4     1452        1425   
10               17  2008      1           3          4      754         745   
11               18  2008      1           3          4     1323        1255   
12               19  2008      1           3          4     1416        1325   
13               21  2008      1           3          4     1657        1625   
14               22  2008      1           3          4     1900        1840   
15               23  2008      1           3          4     1039        1030   
16               25  2008      1           3          4     1520        1455   
17               26  2008      1           3          4     1422        1255   
18               27  2008      1           3          4     1954        1925   
19               30  2008      1           3          4     2107        1945   
20               33  2008      1           3          4     1312        1300   
21               34  2008      1           3          4     1449        1430   
22               35  2008      1           3          4     1634        1555   
23               37  2008      1           3          4     1812        1650   
24               38  2008      1           3          4     1127        1105   
25               39  2008      1           3          4     1424        1355   
26               40  2008      1           3          4     1326        1230   
27               41  2008      1           3          4     1749        1725   
28               42  2008      1           3          4      726         720   
29               43  2008      1           3          4      646         640   
...             ...   ...    ...         ...        ...      ...         ...   
1048545     3504962  2008      6          29          7     1310        1300   
1048546     3504963  2008      6          30          1     1337        1300   
1048547     3504994  2008      6           1          7     1340        1245   
1048548     3504995  2008      6           2          1     1330        1245   
1048549     3504998  2008      6           5          4     1357        1245   
1048550     3505003  2008      6          10          2     1254        1245   
1048551     3505004  2008      6          11          3     1304        1245   
1048552     3505006  2008      6          13          5     1255        1245   
1048553     3505010  2008      6          17          2     1424        1245   
1048554     3505011  2008      6          18          3     1255        1245   
1048555     3505012  2008      6          19          4     1259        1245   
1048556     3505014  2008      6          21          6     1301        1245   
1048557     3505015  2008      6          22          7     1305        1245   
1048558     3505018  2008      6          25          3     1259        1245   
1048559     3505021  2008      6          28          6     1308        1245   
1048560     3505022  2008      6          29          7     1308        1245   
1048561     3505024  2008      6           1          7     1559        1535   
1048562     3505027  2008      6           4          3     1617        1535   
1048563  

In [5]:
X=d['DepDelay']
y=d['ArrDelay']

In [6]:
X

0           8
1          19
2           8
3          34
4          25
5          67
6           6
7          94
8           9
9          27
10          9
11         28
12         51
13         32
14         20
15          9
16         25
17         87
18         29
19         82
20         12
21         19
22         39
23         82
24         22
25         29
26         56
27         24
28          6
29          6
           ..
1048545    10
1048546    37
1048547    55
1048548    45
1048549    72
1048550     9
1048551    19
1048552    10
1048553    99
1048554    10
1048555    14
1048556    16
1048557    20
1048558    14
1048559    23
1048560    23
1048561    24
1048562    42
1048563     8
1048564    48
1048565    48
1048566    10
1048567    34
1048568    41
1048569    42
1048570    16
1048571    20
1048572    20
1048573    32
1048574    33
Name: DepDelay, Length: 1048575, dtype: int64

In [7]:
y


0          -14.0
1            2.0
2           14.0
3           34.0
4           11.0
5           57.0
6            1.0
7           80.0
8           11.0
9           15.0
10         -15.0
11          16.0
12          37.0
13          19.0
14           6.0
15          -7.0
16          14.0
17          47.0
18           4.0
19          64.0
20          -4.0
21          -5.0
22          14.0
23          72.0
24           5.0
25          11.0
26          29.0
27         -11.0
28         -22.0
29         -26.0
           ...  
1048545     -3.0
1048546     29.0
1048547     40.0
1048548     49.0
1048549     73.0
1048550     -5.0
1048551     14.0
1048552     -1.0
1048553    134.0
1048554     17.0
1048555      4.0
1048556      9.0
1048557     32.0
1048558     25.0
1048559     17.0
1048560     35.0
1048561      6.0
1048562     30.0
1048563     -3.0
1048564     42.0
1048565     48.0
1048566     29.0
1048567     27.0
1048568     39.0
1048569     47.0
1048570      8.0
1048571     12.0
1048572      2

In [8]:
X=X.values.reshape(-1,1)

In [9]:
X

array([[ 8],
       [19],
       [ 8],
       ...,
       [20],
       [32],
       [33]], dtype=int64)

# splitting data into training and testing set

In [10]:
mean_dep_delay=d['DepDelay'].mean()

In [11]:
d['DepDelay'].fillna('mean_dep_delay',inplace=True)


In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=1)

In [14]:
X_train

array([[24],
       [34],
       [17],
       ...,
       [25],
       [78],
       [19]], dtype=int64)

In [15]:
y_train

109881      18.0
893552      68.0
695917       9.0
652905     118.0
666397      14.0
394973      -1.0
599286      45.0
746605      69.0
827928      96.0
176314      42.0
788152      72.0
193069      -3.0
817926      15.0
562633       1.0
496269      25.0
692581     141.0
242349      46.0
989277      61.0
565880      -1.0
301455       5.0
445079      26.0
725979      64.0
551345       7.0
94293       49.0
991032      39.0
411125      43.0
98609       34.0
704189      12.0
335617      44.0
523592      -2.0
           ...  
1005966      7.0
188317       9.0
365212      35.0
806378     226.0
401660      29.0
457611     104.0
575956       4.0
691090      37.0
176485      32.0
21758      -10.0
513300      35.0
1041586     38.0
1015065     49.0
167302     100.0
293372      10.0
436973      66.0
925255     143.0
966604     132.0
413825       8.0
229520     185.0
21440       15.0
117583      41.0
73349      145.0
371403       9.0
836489       8.0
491263      12.0
791624      69.0
470924      24

In [16]:
X_train=X_train.reshape((-1,1))

In [17]:
X_train

array([[24],
       [34],
       [17],
       ...,
       [25],
       [78],
       [19]], dtype=int64)

In [18]:
from sklearn import linear_model as lm

In [19]:
model=lm.LinearRegression()
results=model.fit(X_train,y_train)
results

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

AttributeError: 'DataFrame' object has no attribute 'd'